remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

title: SQL Learning Guide
description: Step-by-step SQL Learning Documentation

show_downloads: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
