remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: SQL Learning Guide
description: Step-by-step SQL Learning Documentation
show_downloads: false
include: 
  - _pages
