remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme # Ensure this is included

title: SQL Learning Guide
description: Step-by-step SQL Learning Documentation

show_downloads: false

# If you want navigation links, add them under `navigation` (for some themes)
navigation:
  - title: Home
    url: /
  - title: Syntax Basics
    url: /01_Syntax_Basics.md
  - title: CRUD & Joins
    url: /02_CRUD_Joins_Aggregations.md
  - title: Indexes & Constraints
    url: /03_Indexes_Constraints.md
  - title: Query Optimization
    url: /04_Query_Optimization.md
  - title: Stored Procedures
    url: /05_Stored_Procedures_Functions.md
  - title: Security & Backup
    url: /06_Security_Backup.md
